framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: restaurant_app
        
        # Filesystem cache (compatible partout)
        app: cache.adapter.filesystem
        
        # Pools de cache optimisés
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
            doctrine.system_cache_pool:
                adapter: cache.adapter.filesystem
